GET http://localhost:25565/hello
Accept: application/json

> {%
client.test("test-hello", function (){
    client.log("test hello");
    //client.log(JSON.stringify(response.body));
    client.assert(response.status == 200, "response status is not 200");
    client.assert(response.body == "hello-world", "response is not hello world")
})
%}

###

POST http://localhost:25565/hello/post
Content-Type: application/x-www-form-urlencoded

name=good

###

GET http://localhost:25565/deck/list?name=Atraxa

###

GET http://localhost:25565/editor/dialog/get?name=test1

###